## code to prepare `sources_to_exclude` dataset goes here

sources_to_exclude <- c("m.facebook.com",
                        "facebook.com",
                        "drehscheibe-online.de",
                        "disq.us",
                        "googleapis.com",
                        "t.co",
                        "l.facebook.com",
                        "baidu.com",
                        "getpocket.com",
                        "news.google.com",
                        "intopic.it",
                        "it.wikipedia.org",
                        "it.m.wikipedia.org",
                        "en.wikipedia.org",
                        "en.m.wikipedia.org",
                        "linkedin.com",
                        "c.newsnow.co.uk",
                        "lm.facebook.com",
                        "uploads.knightlab.com",
                        "mobimailtin.tim.it",
                        "it.search.yahoo.com",
                        "feedly.com",
                        "mail.tiscali.it",
                        "247.libero.it",
                        "search-duo.com",
                        "qoolg.com",
                        "youtube.com",
                        "mobimailtin.tim.it",
                        "l.instagram.com",
                        "qwant.com",
                        "twitter.com",
                        "mail.google.com",
                        "cn.bing.com",
                        "sync.opera.com",
                        "webmailtin.pc.tim.it",
                        "ecosia.org",
                        "bitly.com",
                        "duckduckgo.com")

usethis::use_data(sources_to_exclude, overwrite = TRUE)
